<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Models\Meme.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="wwwroot\Models\Meme.cs" />
  </ItemGroup>

</Project>
